[2025-05-20T23:11:30.866+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.extract_reddit scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T23:11:30.871+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.extract_reddit scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T23:11:30.872+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-20T23:11:30.882+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_reddit> on 2025-05-19 00:00:00+00:00
[2025-05-20T23:11:30.885+0000] {standard_task_runner.py:57} INFO - Started process 45 to run task
[2025-05-20T23:11:30.887+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'extract_reddit', 'scheduled__2025-05-19T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpd3m2wafe']
[2025-05-20T23:11:30.888+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask extract_reddit
[2025-05-20T23:11:30.918+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.extract_reddit scheduled__2025-05-19T00:00:00+00:00 [running]> on host c1d902c35895
[2025-05-20T23:11:30.963+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='extract_reddit' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T00:00:00+00:00'
[2025-05-20T23:11:30.964+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: reddit_pipeline() missing 1 required positional argument: 'filename'
[2025-05-20T23:11:30.969+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=extract_reddit, execution_date=20250519T000000, start_date=20250520T231130, end_date=20250520T231130
[2025-05-20T23:11:30.975+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task extract_reddit (reddit_pipeline() missing 1 required positional argument: 'filename'; 45)
[2025-05-20T23:11:30.985+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-20T23:11:30.997+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T23:44:49.711+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.extract_reddit scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T23:44:49.718+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.extract_reddit scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T23:44:49.719+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-20T23:44:49.729+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_reddit> on 2025-05-19 00:00:00+00:00
[2025-05-20T23:44:49.735+0000] {standard_task_runner.py:57} INFO - Started process 46 to run task
[2025-05-20T23:44:49.734+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'extract_reddit', 'scheduled__2025-05-19T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpnem4cfl9']
[2025-05-20T23:44:49.735+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask extract_reddit
[2025-05-20T23:44:49.762+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.extract_reddit scheduled__2025-05-19T00:00:00+00:00 [running]> on host 0bdedd2b68b9
[2025-05-20T23:44:49.808+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='extract_reddit' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T00:00:00+00:00'
[2025-05-20T23:44:49.810+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: reddit_pipeline() missing 1 required positional argument: 'filename'
[2025-05-20T23:44:49.814+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=extract_reddit, execution_date=20250519T000000, start_date=20250520T234449, end_date=20250520T234449
[2025-05-20T23:44:49.823+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task extract_reddit (reddit_pipeline() missing 1 required positional argument: 'filename'; 46)
[2025-05-20T23:44:49.832+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-20T23:44:49.843+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
