[2025-05-21T00:38:35.187+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.extract_reddit manual__2025-05-21T00:00:28.315502+00:00 [queued]>
[2025-05-21T00:38:35.212+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.extract_reddit manual__2025-05-21T00:00:28.315502+00:00 [queued]>
[2025-05-21T00:38:35.212+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 3
[2025-05-21T00:38:35.246+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_reddit> on 2025-05-21 00:00:28.315502+00:00
[2025-05-21T00:38:35.257+0000] {standard_task_runner.py:57} INFO - Started process 75 to run task
[2025-05-21T00:38:35.266+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'extract_reddit', 'manual__2025-05-21T00:00:28.315502+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpozbevd2r']
[2025-05-21T00:38:35.274+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask extract_reddit
[2025-05-21T00:38:35.397+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_reddit_pipeline.extract_reddit manual__2025-05-21T00:00:28.315502+00:00 [running]> on host 0bdedd2b68b9
[2025-05-21T00:38:35.817+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='extract_reddit' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T00:00:28.315502+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T00:00:28.315502+00:00'
[2025-05-21T00:38:35.818+0000] {logging_mixin.py:151} INFO - Connected to Reddit API successfully.
[2025-05-21T00:38:36.484+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 14, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
  File "/opt/airflow/etls/reddit_etl.py", line 25, in extract_posts
    post = {key: post_dict[key] for key in POST_FIELDS}
  File "/opt/airflow/etls/reddit_etl.py", line 25, in <dictcomp>
    post = {key: post_dict[key] for key in POST_FIELDS}
KeyError: 'text'
[2025-05-21T00:38:36.489+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=extract_reddit, execution_date=20250521T000028, start_date=20250521T003835, end_date=20250521T003836
[2025-05-21T00:38:36.496+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task extract_reddit ('text'; 75)
[2025-05-21T00:38:36.515+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-21T00:38:36.565+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
